[package]
name = "i3-alt-tab"
version = "0.1.0"
authors = ["Anthony Palmer <AnthonyP4312@gmail.com>"]

[dependencies]
serde_json = "1.0.21"
serde_derive = "1.0.66"
serde = "1.0.66"
structopt = "0.2.13"
strum = "0.11.0"
strum_macros = "0.11.0"
